# Original Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# 
# The theme uses the gruvbox dark palette with standard contrast: github.com/morhetz/gruvbox

"annotation" = { fg = "fg1" }

"attribute" = { fg = "aqua1", modifiers = ["italic"] }

"comment" = { fg = "gray" }

"constant" = { fg = "yellow1", modifiers = ["bold"] }
"constant.builtin" = { fg = "yellow1", modifiers = ["bold"] }
"constant.character" = { fg = "green1", modifiers = ["bold"] }
"constant.character.escape" = { fg = "fg1", modifiers = ["bold"] }
"constant.macro" = { fg = "red1", modifiers = ["bold"] }
"constructor" = { fg = "yellow1", modifiers = ["bold"] }

"definition" = { underline = { color = "aqua1" } }

"diagnostic" = { underline = { color = "orange1" } }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"diagnostic.error" = { underline = { color = "red1", style = "line" } }
"diagnostic.hint" = { underline = { color = "blue0", style = "line" } }
"diagnostic.info" = { underline = { color = "yellow1", style = "line" } }
"diagnostic.warning" = { underline = { color = "orange1", style = "line" } }
# "diagnostic.unnecessary" = { modifiers = ["dim"] }  # do not remove this for future resolving

"error" = { fg = "red1" }
"hint" = { fg = "blue0" }
"info" = { fg = "yellow1" }
"warning" = { fg = "orange1" }

"diff.delta" = { fg = "yellow1" }
"diff.minus" = { fg = "red1" }
"diff.plus" = { fg = "green1" }

"function" = { fg = "blue0", modifiers = ["bold"] }
"function.builtin" = { fg = "blue0", modifiers = ["bold"] }
"function.method" = { fg = "blue0", modifiers = ["bold"] }
"function.macro" = { fg = "blue0", modifiers = ["bold"] }
"function.special" = { fg = "blue0", modifiers = ["bold"] }

"keyword" = { fg = "purple1" }
"keyword.directive" = { fg = "purple1" }
"keyword.control" = { fg = "purple1" }
"keyword.control.conditional" = { fg = "purple1" }
"keyword.control.repeat" = { fg = "purple1" }
"keyword.control.import" = { fg = "purple1" }
"keyword.control.return" = { fg = "purple1" }
"keyword.control.exception" = { fg = "purple1" }
"keyword.operator" = { fg = "purple1" }
"keyword.function" = { fg = "purple1" }
"keyword.storage" = { fg = "purple1" }
"keyword.storage.type" = { fg = "purple1" }
"keyword.storage.modifier" = { fg = "purple1" }

"label" = "yellow1"

"markup" = "fg1"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "fg1"
"markup.heading.marker" = "fg3"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "purple1"
"markup.link.url" = { fg = "purple1", modifiers = ["underlined"] }
"markup.link.label" = { fg = "purple1", modifiers = ["underlined"] }
"markup.raw" = "red1"
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.quote" = "green1"

"module" = { fg = "aqua1" }

"namespace" = "fg2"

"operator" = "fg0"

"punctuation" = "fg2"
"punctuation.delimiter" = "fg3"
"punctuation.bracket" = "fg3"
"punctuation.special" = "purple1"

"special" = { fg = "purple1" }

"string" = "green1"
"string.regexp" = { fg = "green1", modifiers = ["bold"] }
"string.special" = { fg = "green1", modifiers = ["bold"] }
"string.special.path" = { fg = "green1", modifiers = ["bold"] }
"string.special.url" = { fg = "green1", modifiers = ["underlined"] }
"string.special.symbol" = { fg = "green1", modifiers = ["bold"] }

"tag" = "red1"

"tabstop" = { bg = "bg1" }

"type" = { fg = "yellow1" }

# "ui.background" = { bg = "bg0" }
# "ui.bufferline" = { fg = "fg1", bg = "bg1" }
# "ui.bufferline.active" = { fg = "bg0", bg = "yellow0" }
# "ui.bufferline.background" = { bg = "bg2" }

"ui.cursor" = { bg = "bg1" }
# "ui.cursor.insert" = { fg = "bg1", bg = "blue0" }
# "ui.cursor.normal" = { fg = "bg1", bg = "gray" }
# "ui.cursor.select" = { fg = "bg1", bg = "orange0" }
"ui.cursor.match" = { bg = "bg3" }

"ui.cursor.primary" = { modifiers = ["reversed", "bold"] }
# "ui.cursor.primary.insert" = { fg = "bg1", bg = "blue1" }
# "ui.cursor.primary.normal" = { fg = "bg1", bg = "fg3" }
# "ui.cursor.primary.select" = { fg = "bg1", bg = "orange1" }

"ui.cursorline" = { bg = "bg1" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }

"ui.debug.breakpoint" = { fg = "red1" }
"ui.debug.active"  = { fg = "red1" }
 
# "ui.gutter" = { bg = "bg0" }
# "ui.gutter.selected" = { bg = "bg0" }

"ui.help" = { fg = "fg2", bg = "bg0" }
"ui.highlight.frameline" = { fg = "red1" }
"ui.linenr" = { fg = "bg4" }
"ui.linenr.selected" = { fg = "yellow1", modifiers = ["bold"] }
"ui.menu" = { fg = "fg2", bg = "bg0" }
"ui.menu.selected" = { fg = "bg1", bg = "purple1", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "fg2", bg = "bg1" }
"ui.popup" = { bg = "bg0" }
"ui.popup.info" = { bg = "bg0" }
"ui.picker.header.column" = { underline.style = "line" }
"ui.picker.header.column.active" = { modifiers = ["bold"], underline.style = "line" }
"ui.selection" = { bg = "bg1" }
"ui.selection.primary" = { bg = "bg1", modifiers = ["bold"] }

"ui.statusline" = { fg = "fg0" }
"ui.statusline.inactive" = { fg = "fg2" }
"ui.statusline.insert" = { bg = "blue0", fg = "bg0" }
"ui.statusline.normal" = { bg = "green1", fg = "bg0" }
"ui.statusline.select" = { bg = "yellow1", fg = "bg0" }

# "ui.text" = { fg = "fg2", bg = "bg0" }
# "ui.text.directory" = { fg = "fg2", bg = "bg0" }
"ui.virtual.inlay-hint" = { fg = "gray" }
"ui.virtual.jump-label" = { fg = "purple1", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = "gray"
"ui.virtual.wrap" = { fg = "gray" }
"ui.virtual.indent-guide" = { fg = "bg1" }
# "ui.window" = { bg = "bg0" }

"variable" = "fg2"
"variable.builtin" = "yellow1"
"variable.parameter" = "fg2"
"variable.other.member" = "fg2"


[palette]
bg0 = "#282828" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1" # main foreground
fg3 = "#bdae93"
fg4 = "#a89984"

gray = "#928374"

red0    = "#cc241d" # neutral
red1    = "#fb4934" # bright
green0  = "#98971a"
green1  = "#b8bb26"
yellow0 = "#d79921"
yellow1 = "#fabd2f"
blue0   = "#458588"
blue1   = "#83a598"
purple0 = "#b16286"
purple1 = "#d3869b"
aqua0   = "#689d6a"
aqua1   = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"
