# Original Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with standard contrast: github.com/morhetz/gruvbox

"attribute" = "red1" # class attributes idk fuck OOP
"keyword" = { fg = "red1" }
"keyword.directive" = "red1"
"namespace" = "purple0"
"type" = { fg = "yellow1", modifiers = ["bold"] }
"type.builtin" = { fg = "yellow1" }
"constructor" = { fg = "yellow1", modifiers = ["bold"] } # in Rust: Some(_), etc.
# "constant" = { fg = "yellow1", mo1ifiers = ["bold"] }
"constant.builtin" = { fg = "yellow1", modifiers = ["bold"] }
"constant.character" = { fg = "green1" }
"constant.character.escape" = { fg = "fg2", modifiers = ["bold"] } # Don't work in Rust
"constant.numeric" = "yellow1"
"string" = "green1"
"string.regexp" = { fg = "green1", modifiers = ["bold"] }
"string.special.path" = { fg = "green1", modifiers = ["bold"] }
"string.special.url" = { fg = "green1", modifiers = ["underlined"] }
"string.special.symbol" = { fg = "green1", modifiers = ["bold"] }
# "comment" = { fg = "gray1", modifiers = ["italic"] }
"comment" = { fg = "gray1" }
"comment.line" = { fg = "gray1", modifiers = ["italic"] }
"comment.block" = { fg = "gray1", modifiers = ["italic"] }
"variable" = "fg2"
"variable.builtin" = "yellow1"
"variable.parameter" = "fg2"
"variable.other.member" = "fg2"
"label" = "aqua0"
"punctuation" = "fg2"
"punctuation.delimiter" = "fg4"
"punctuation.bracket" = "fg4"
"punctuation.special" = "fg1"
"keyword.control" = { fg = "red1" }
"keyword.control.conditional" = { fg = "red1" }
"keyword.control.repeat" = { fg = "red1" }
"keyword.control.import" = { fg = "red1" }
"keyword.control.return" = { fg = "red1" }
"keyword.control.exception" = { fg = "red1" }
"keyword.operator" = { fg = "red1" }
"keyword.function" = { fg = "red1" }
"keyword.storage" = { fg = "red1" }
"keyword.storage.type" = { fg = "red1" }
"keyword.storage.modifier" = { fg = "red1" }
"operator" = "fg0"
"function" = { fg = "blue0", modifiers = ["bold"] }
"function.builtin" = { fg = "yellow1", modifiers = ["bold"] }
"function.method" = { fg = "blue0", modifiers = ["bold"] }
"function.macro" = { fg = "blue0", modifiers = ["bold"] }
"function.special" = { fg = "blue0", modifiers = ["bold"] } # C preprocessor functions
"tag" = "red1" # HTML etc.
"markup" = "fg4"
"markup.heading" = "fg0"
"markup.heading.marker" = "fg4"
"markup.bold" = { modifiers = ["bold"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow1", modifiers = ["underlined"] }
"markup.link.label" = { fg = "yellow1", modifiers = ["underlined"] }
"markup.link.text" = "purple0"
"markup.quote" = "green1"
"markup.raw" = "red1"
"diff" = "fg4"
"diff.plus" = "green1"
"diff.minus" = "red1"
"diff.delta" = "orange1"
"diff.delta.moved" = "red1"

# Editor Interface

## UI
# The following are commented out to allow a transparent background
# "ui.background" = { bg = "bg0" }
# "ui.background.separator" = { bg = "bg0" }
# "ui.cursor.insert" = { bg = "bg0" }
# "ui.cursor.select" = { bg = "bg0" }
# "ui.gutter" = { bg = "bg0" }
# "ui.statusline" = { fg = "fg0", bg = "bg0" }
# "ui.gutter.selected" = { bg = "bg0" } # current line in gutter
"ui.debug.breakpoint" = { fg = "red1" } # Breakpoint indicator, found in the gutter
"ui.debug.active"  = { fg = "red1" } # Indicator for the line at which debugging execution is paused at, found in the gutter
"ui.highlight.frameline" = { fg = "red1" } # Line at which debugging execution is paused at
"ui.selected" = { fg = "red1" }
"ui.statusline" = { fg = "fg0" }
"ui.cursor.match" = { bg = "bg3" }
"ui.cursor" = { bg = "bg1" }
"ui.cursor.primary" = { modifiers = ["reversed", "bold"] }
"ui.linenr" = { fg = "bg4" }
"ui.linenr.selected" = { fg = "yellow1", modifiers = ["bold"] }
# "ui.statusline.inactive" = { fg = "fg2", bg = "bg0" }
"ui.statusline.inactive" = { fg = "fg2" }
"ui.statusline.normal" = { bg = "green1", fg = "bg0" }
"ui.statusline.insert" = { bg = "blue0", fg = "bg0" }
"ui.statusline.select" = { bg = "yellow1", fg = "bg0" }
"ui.statusline.separator" = { bg = "red1", fg = "bg0" } # ???
# "ui.popup" = { bg = "bg1" }
# "ui.popup.info" = { bg = "bg1" }
# "ui.window" = { bg = "bg0" } # split separator - commented out for transparency
"ui.help" = { fg = "fg2", bg = "bg1" } # help windows
# "ui.text" = { fg = "fg2", bg = "bg0" }
"ui.virtual.ruler" = { bg = "bg1" }
# "ui.virtual.wrap" = { fg = "fg4" }
"ui.virtual.inlay-hint" = { fg = "fg4" }
"ui.virtual.inlay-hint.parameter" = { fg = "gray1" }
"ui.virtual.inlay-hint.type" = { fg = "gray1" }
"ui.virtual.jump-label" = { fg = "yellow0", modifiers = ["bold", "italic", "alkjwlkjad"] }
# below is uncommented to appropriately highlight selected whitespace
# "ui.virtual.whitespace" = { fg = "purple1", bg = "bg0" } # :set whitespace.render all
# this foreground is undefined to appropriately render selected indent guidelines
"ui.virtual.indent-guide" = { fg = "bg1" }
"ui.menu" = { fg = "fg2", bg = "bg1" }
"ui.menu.selected" = { fg = "bg1", bg = "blue1", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "fg2", bg = "bg1" }
"ui.selection" = { bg = "bg1" }
"ui.selection.primary" = { bg = "bg1", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.cursorcolumn.primary" = { bg = "bg1" }
"ui.cursorcolumn.secondary" = { bg = "bg1" }

## UI diagnostics in gutter
# "warning" = { fg = "orange1", bg = "bg0" }
# "error" = { fg = "red1", bg = "bg0" }
# "info" = { fg = "aqua1", bg = "bg0" }
# "hint" = { fg = "blue1", bg = "bg0" }
"warning" = { fg = "orange1" }
"error" = { fg = "red1" }
"info" = { fg = "aqua1" }
"hint" = { fg = "blue1" }

## UI diagnostics in editing area
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.warning" = { underline = { style = "line", color = "orange1" } }
"diagnostic.error" = { underline = { style = "line", color = "red1" } }
"diagnostic.info" = { underline = { style = "line", color = "aqua1" } }
"diagnostic.hint" = { underline = { style = "line", color = "blue1" } }

"ui.virtual.wrap" = { fg = "bg2" }

[palette]
bg0 = "#282828" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1" # main foreground
fg3 = "#bdae93"
fg4 = "#a89984" # gray0

gray0 = "#a89984"
gray1 = "#928374"

red0    = "#cc241d" # neutral
red1    = "#fb4934" # bright
green0  = "#98971a"
green1  = "#b8bb26"
yellow0 = "#d79921"
yellow1 = "#fabd2f"
blue0   = "#458588"
blue1   = "#83a598"
purple0 = "#b16286"
purple1 = "#d3869b"
aqua0   = "#689d6a"
aqua1   = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"
