#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
# Bars
killall polybar
polybar --config=/home/notroot/.config/polybar/config.ini main &
# polybar --config=/home/notroot/.config/polybar/config.ini legionmon &
# polybar --config=/home/notroot/.config/polybar/config.ini msimon &
# polybar --config=/home/notroot/.config/polybar/config.ini hpmon &
xsetroot -solid "#2e3440"

# Workspaces

# One monitor
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9

# Four monitors
# bspc monitor DP-4 -d 7 8
# bspc monitor HDMI-0 -d 5 6
# bspc monitor DP-0 -d 1 2
# bspc monitor DP-2 -d 3 4

# Three monitors
# bspc monitor DP-4 -d 7 8 9
# bspc monitor DP-0 -d 1 2 3
# bspc monitor DP-2 -d 4 5 6

# BSPWM Configuration
bspc config border_width        4
bspc config window_gap          12
bspc config top_padding         52 # Bar padding + bar + window gap

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Zathura state=tiled
bspc rule -a mpv state=pseudo_tiled

bspc config remove_disabled_monitors

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color   '#2e3440'
bspc config focused_border_color  '#4c566a'
bspc config active_border_color   '#2e3440'
bspc config presel_feedback_color '#4c566a'
