#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
killall polybar
xsetroot -solid "#282828"

export MONCOUNT="$(xrandr | grep " connected " | wc -l)"

# Workspaces

# One monitor
if [ "$MONCOUNT" -eq 1 ]; then
	polybar --reload --config=/home/notroot/.config/polybar/config.ini main &
	bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9
fi


# Four monitors
if [ "$MONCOUNT" -eq 4 ]; then
	polybar --reload --config=/home/notroot/.config/polybar/config.ini main &
	bspc monitor DP-4 -d 7 8

	polybar --reload --config=/home/notroot/.config/polybar/config.ini hpmon &
	bspc monitor HDMI-0 -d 5 6

	polybar --reload --config=/home/notroot/.config/polybar/config.ini legionmon &
	bspc monitor DP-0 -d 1 2

	polybar --reload --config=/home/notroot/.config/polybar/config.ini msimon &
	bspc monitor DP-2 -d 3 4
fi

# Three monitors
if [ "$MONCOUNT" -eq 3 ]; then
	polybar --reload --config=/home/notroot/.config/polybar/config.ini main &
	bspc monitor DP-4 -d 7 8 9

	polybar --reload --config=/home/notroot/.config/polybar/config.ini legionmon &
	bspc monitor DP-0 -d 1 2 3

	polybar --reload --config=/home/notroot/.config/polybar/config.ini msimon &
	bspc monitor DP-2 -d 4 5 6
fi

# BSPWM Configuration
bspc config border_width        4
bspc config window_gap          12
bspc config top_padding         52 # Bar padding + bar + window gap

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Zathura state=tiled
bspc rule -a mpv state=pseudo_tiled

bspc config remove_disabled_monitors

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color   '#282828'
bspc config focused_border_color  '#928374'
bspc config active_border_color   '#282828'
bspc config presel_feedback_color '#928374'
