theme = "mygruvbox"

[editor]
true-color = true
line-number = "relative"
color-modes = true
scrolloff = 7
idle-timeout = 50
bufferline = "multiple"
mouse = false
popup-border = "all"
indent-heuristic = "tree-sitter"
end-of-line-diagnostics = "hint"
# rulers = [80]

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"
# other-lines = "error"

[editor.soft-wrap]
enable = true
wrap-indicator = "←→"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
space = { w = ":w", W = ":toggle whitespace.render all none", q = ":q", i = ":toggle lsp.display-inlay-hints", x = ":bc" }
esc = ["collapse_selection", "keep_primary_selection"]
ret = "goto_word"
minus = { s = ":sh git status", p = ":sh git fetch && git pull", d = ":sh git diff", l = ":sh git log -n 3", b = ":sh git branch" }

# Use modal editing, pussy
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

# [editor.whitespace.render]
# space = "none"
# tab = "none"
# newline = "none"
# nbsp = "none"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# tab = "→"
# newline = "⏎"
# tabpad = "·"
